# Display commands
@help:
   just --list


# Set up repo
@init:
  npm install


# Dev server
@serve:
  npm run dev


# Build production site
@build:
  npm run build


# Release static site production
@release: build
  rsync -avz \
    --exclude=.DS_Store \
    build/ \
    tools:~/www/gtsf-ui
