# Display commands
@help:
	just --list


# Set up repo
@init:
  uv sync


# Dev server
@serve:
  uv run uvicorn main:app --reload


# Release backend code to production server
@release:
  rsync -avz \
    --delete \
    --exclude=__pycache__ \
    --exclude=.DS_Store \
    --exclude=.venv \
    backend/ \
    tools:~/gtsf-backend
